<?php

/**
 * @package BeeQuiz
 */

class Quiz_Shortcodes extends Quiz_Properties
{
    public function init() {
        add_shortcode( $this->prefix . '_quiz', array( $this, 'quiz' ) );
        add_shortcode( $this->prefix . '_register', array( $this, 'register' ) );
        add_shortcode( $this->prefix . '_python', array( $this, 'python' ) );
    }

    public function quiz( $atts, $content = null ) {
        $html  = '<div id="quiz-container" class="common-container">';
        $html .=     '<div id="quiz__splash-screen" class="common__splash-screen">';
        $html .=         '<i class="fas fa-spinner is-animated" id="quiz__loader"></i>';
        $html .=     '</div>';
        $html .=     '<div class="container">';
        $html .=         '<ol id="quiz__progress-bar" class="common__progress-bar">';
        $html .=             '<li id="quiz__progress-bar__1" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__2" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__3" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__4" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__5" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__6" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__7" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__8" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__9" class="incomplete"></li>';
        $html .=             '<li id="quiz__progress-bar__10" class="incomplete"></li>';
        $html .=         '</ol>';
        $html .=         '<h5 id="quiz__progress-text" class="common__progress-text is-visible">Question <span id="quiz__progress-counter"></span> of 10</h5>';
        $html .=         '<div id="quiz__question-container" class="is-visible">';
        $html .=             '<h2 id="quiz__question"></h2>';
        $html .=         '</div>';
        $html .=         '<ul id="quiz__answers" class="is-visible">';
        $html .=             '<li class="quiz__answer"><a href="javascript:void(0);" class="btn btn-default" id="quiz__answers__1" role="button"></a></li>';
        $html .=             '<li class="quiz__answer"><a href="javascript:void(0);" class="btn btn-default" id="quiz__answers__2" role="button"></a></li>';
        $html .=             '<li class="quiz__answer"><a href="javascript:void(0);" class="btn btn-default" id="quiz__answers__3" role="button"></a></li>';
        $html .=         '</ul>';
        $html .=     '</div>';
        $html .=     '<div id="quiz__results-screen" class="common__results-screen">';
        $html .=         '<div class="results-screen__text-container container">';
        $html .=             '<h3 id="quiz__results-screen__match">You have a match!</h3>';
        $html .=             '<div id="quiz__results-screen__picture"></div>';
        $html .=             '<h5 id="quiz__results-screen__name"></h5>';
        $html .=             '<p id="quiz__results-screen__message">Send <span id="quiz__results-screen__name-span"></span> an email and start the conversation! Just click the button below.</p>';
        $html .=             '<a id="quiz__results-screen__email" class="btn btn-default" href="#" id="quiz__results-screen__email"></a>';
        $html .=         '</div>';
        $html .=     '</div>';
        $html .= '</div>';

        return $html;
    }

    public function register( $atts, $content = null ) {
        $html  = '<div id="register-container" class="common-container">';
        $html .=     '<div id="register__splash-screen" class="common__splash-screen is-hidden">';
        $html .=         '<div class="container">';
        $html .=             '<h1>Register your Organisation</h1>';
        $html .=             '<p>Thanks for taking interest in StudentBee. Click below to register your organisation with StudentBee.</p>';
        $html .=             '<a href="javascript:void(0);" class="btn btn-default">Start</a>';
        $html .=         '</div>';
        $html .=     '</div>';
        $html .=     '<div class="container">';
        $html .=         '<ol id="register__progress-bar" class="common__progress-bar">';
        $html .=             '<li id="register__progress-bar__1" class="current"></li>';
        $html .=             '<li id="register__progress-bar__2" class="incomplete"></li>';
        $html .=             '<li id="register__progress-bar__3" class="incomplete"></li>';
        $html .=             '<li id="register__progress-bar__4" class="incomplete"></li>';
        $html .=         '</ol>';
        $html .=         '<h5 id="register__progress-text" class="common__progress-text is-visible">Screen <span id="register__progress-counter">1</span> of 4: <span id="register__progress-description">Organisation Details</span></h5>';
        $html .=         '<div id="register__form-container">';
        $html .=             '<form id="register_registration_form" enctype="multipart/form-data" novalidate>';
        $html .=                 '<input type="hidden" name="action" value="submit_registration_form" />';
        $html .=                 wp_nonce_field( 'submit_registration_form', '_register_nonce' );
        $html .=                 '<div id="register__screen__1" class="register__screen is-visible">';
        $html .=                     '<div id="register_organisation_name_group" class="form-group">';
        $html .=                         '<label for="register_organisation_name">';
        $html .=                             'Organisation Name';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_name" id="register_organisation_name" class="form-control" required maxlength="140" />';
        $html .=                         '<div class="invalid-feedback">';
        $html .=                             'Names must be no more than 140 characters.';
        $html .=                         '</div>';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_description_group" class="form-group">';
        $html .=                         '<label for="register_organisation_description">';
        $html .=                             'Organisation Description';
        $html .=                         '</label>';
        $html .=                         '<textarea name="register_organisation_description" id="register_organisation_description" class="form-control" aria-describedby="register_organisation_description_help" required maxlength="500"></textarea>';
        $html .=                         '<div class="invalid-feedback">';
        $html .=                             'Descriptions must be no more than 500 characters.';
        $html .=                         '</div>';
        $html .=                         '<small id="register_organisation_description_help" class="form-text text-muted">Students will see this when they match with you, so tailor it to your target audience.</small>';
        $html .=                     '</div>';
        $html .=                     '<a href="javascript:void(0);" id="register__next-screen__1" class="btn btn-default register__next-screen disabled" aria-disabled="true" tabindex="-1">Continue</a>';
        $html .=                 '</div>';
        $html .=                 '<div id="register__screen__2" class="register__screen is-hidden is-removed">';
        $html .=                     '<div id="register_organisation_contact_picture_group" class="form-group">';
        $html .=                         '<label for="register_organisation_contact_picture" id="register_organisation_contact_picture_label" class="btn btn-default" role="button">';
        $html .=                             'Upload Contact Picture';
        $html .=                         '</label>';
        $html .=                         '<input type="file" name="register_organisation_contact_picture" id="register_organisation_contact_picture" class="form-control-file" aria-describedby="register_organisation_contact_picture_help" required accept="image/*" />';
        $html .=                         '<div class="invalid-feedback">';
        $html .=                             'Files must be images of size less than 2 MB.';
        $html .=                         '</div>';
        $html .=                         '<small id="register_organisation_contact_picture_help" class="form-text text-muted">When students match with you, they will be asked to contact this person.</small>';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_contact_name_group" class="form-group">';
        $html .=                         '<label for="register_organisation_contact_name">';
        $html .=                             'Contact Name';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_contact_name" id="register_organisation_contact_name" class="form-control" required maxlength="140" />';
        $html .=                         '<div class="invalid-feedback">';
        $html .=                             'Names must be no more than 140 characters.';
        $html .=                         '</div>';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_contact_email_address_group" class="form-group">';
        $html .=                         '<label for="register_organisation_contact_email_address">';
        $html .=                             'Contact Email Address';
        $html .=                         '</label>';
        $html .=                         '<input type="email" name="register_organisation_contact_email_address" id="register_organisation_contact_email_address" class="form-control" required maxlength="140" />';
        $html .=                         '<div class="invalid-feedback">';
        $html .=                             'Please input a valid email address no more than 140 characters in length.';
        $html .=                         '</div>';
        $html .=                     '</div>';
        $html .=                     '<a href="javascript:void(0);" id="register__next-screen__2" class="btn btn-default register__next-screen disabled" aria-disabled="true" tabindex="-1">Continue</a>';
        $html .=                 '</div>';
        $html .=                 '<div id="register__screen__3" class="register__screen is-hidden is-removed">';
        $html .=                     '<div id="register_organisation_address_lookup_group" class="form-group">';
        $html .=                         '<label for="register_organisation_address_lookup" class="sr-only">';
        $html .=                             'Lookup Postcode';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_address_lookup" id="register_organisation_address_lookup" class="form-control" placeholder="Lookup Postcode" />';
        $html .=                         '<button type="button" id="register_organisation_address_lookup_button" class="btn btn-default" onclick="return false;">';
        $html .=                             'Lookup';
        $html .=                         '</button>';
        $html .=                         '<select id="register_dummy_dropdown" class="form-control" disabled>';
        $html .=                             '<option value="ideal">Select address</option>';
        $html .=                         '</select>';
        $html .=                         '<div class="invalid-feedback">';
        $html .=                             'Please select a valid UK postcode.';
        $html .=                         '</div>';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_address_line_1_group" class="form-group no-label">';
        $html .=                         '<label for="register_organisation_address_line_1" class="sr-only">';
        $html .=                             'Address Line 1';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_address_line_1" id="register_organisation_address_line_1" class="form-control" placeholder="Address Line 1" required maxlength="140" />';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_address_line_2_group" class="form-group no-label">';
        $html .=                         '<label for="register_organisation_address_line_2" class="sr-only">';
        $html .=                             'Address Line 2';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_address_line_2" id="register_organisation_address_line_2" class="form-control" placeholder="Address Line 2" maxlength="140" />';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_address_line_3_group" class="form-group no-label">';
        $html .=                         '<label for="register_organisation_address_line_3" class="sr-only">';
        $html .=                             'Address Line 3';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_address_line_3" id="register_organisation_address_line_3" class="form-control" placeholder="Address Line 3" maxlength="140" />';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_address_town_city_group" class="form-group no-label">';
        $html .=                         '<label for="register_organisation_address_town_city" class="sr-only">';
        $html .=                             'Town/City';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_address_town_city" id="register_organisation_address_town_city" class="form-control" placeholder="Town/City" required maxlength="140" />';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_address_postcode_group" class="form-group no-label">';
        $html .=                         '<label for="register_organisation_address_postcode" class="sr-only">';
        $html .=                             'Postcode';
        $html .=                         '</label>';
        $html .=                         '<input type="text" name="register_organisation_address_postcode" id="register_organisation_address_postcode" class="form-control" placeholder="Postcode" required maxlength="140" />';
        $html .=                     '</div>';
        $html .=                     '<a href="javascript:void(0);" id="register__next-screen__3" class="btn btn-default register__next-screen disabled" aria-disabled="true" tabindex="-1">Continue</a>';
        $html .=                 '</div>';
        $html .=                 '<div id="register__screen__4" class="register__screen is-hidden is-removed">';
        $html .=                     '<div id="register_organisation_permission_group" class="form-group">';
        $html .=                         '<div class="form-check">';
        $html .=                             '<input type="checkbox" name="register_organisation_permission" id="register_organisation_permission" class="form-check-input" value="" required />';
        $html .=                             '<label class="form-check-label" for="register_organisation_permission">';
        $html .=                                 'I have permission to register on behalf of this organisation.';
        $html .=                             '</label>';
        $html .=                             '<span class="custom-checkbox"><i class="fas fa-check"></i></span>';
        $html .=                             '<div class="invalid-feedback">';
        $html .=                                 'You must agree to this statement before submission.';
        $html .=                             '</div>';
        $html .=                         '</div>';
        $html .=                     '</div>';
        $html .=                     '<div id="register_organisation_terms_group" class="form-group">';
        $html .=                         '<div class="form-check">';
        $html .=                             '<input type="checkbox" name="register_organisation_terms" id="register_organisation_terms" class="form-check-input" value="" required />';
        $html .=                             '<label class="form-check-label" for="register_organisation_terms">';
        $html .=                                 'I agree to the StudentBee Terms and Conditions.';
        $html .=                             '</label>';
        $html .=                             '<span class="custom-checkbox"><i class="fas fa-check"></i></span>';
        $html .=                             '<div class="invalid-feedback">';
        $html .=                                 'You must agree to this statement before submission.';
        $html .=                             '</div>';
        $html .=                         '</div>';
        $html .=                     '</div>';
        $html .=                     '<button type="submit" id="register_registration_form_submit" class="btn btn-default">Submit Registration</button>';
        $html .=                 '</div>';
        $html .=             '</form>';
        $html .=         '</div>';
        $html .=     '</div>';
        $html .=     '<div id="register__results-screen" class="common__results-screen">';
        $html .=         '<h3 id="register__results-screen__message">Done!</h3>';
        $html .=     '</div>';
        $html .= '</div>';

        return $html;
    }
}